import XCTest
import SwiftUI
import UIKit
import CapydokuCore
@testable import Capydoku

private final class OriginalVisualIdentity: AnalyticsIdentityStore {
    var value: AnalyticsIdentity?
    func load() -> AnalyticsIdentity? { value }
    func save(_ identity: AnalyticsIdentity) -> Bool { value = identity; return true }
}

@MainActor private final class OriginalVisualEnvironment: ObservableObject {
    @Published var phase: ScenePhase = .active
    @Published var reduceMotion: Bool
    init(reduceMotion: Bool) { self.reduceMotion = reduceMotion }
}

private struct OriginalRewardVisualHarness: View {
    @ObservedObject var model: AppModel
    @ObservedObject var environment: OriginalVisualEnvironment
    var body: some View {
        RootView(reduceMotionOverride: environment.reduceMotion).environmentObject(model)
            .environment(\.scenePhase, environment.phase)
    }
}

@MainActor private final class OriginalRewardVisualRig {
    let directory: URL
    let identity = OriginalVisualIdentity()
    let model: AppModel
    let environment: OriginalVisualEnvironment
    let host: UIHostingController<OriginalRewardVisualHarness>
    let window: UIWindow
    let previousWindow: UIWindow?

    init(reduceMotion: Bool = false, configure: ((AppModel) throws -> Void)? = nil) throws {
        directory = FileManager.default.temporaryDirectory.appendingPathComponent("original-reward-visual-" + UUID().uuidString)
        model = AppModel(saveDirectory: directory, runsTimer: false, feedbackEnabled: false, analyticsIdentityStore: identity)
        model.progress.tutorialCompleted = true
        model.start(level: 1)
        try configure?(model)
        environment = OriginalVisualEnvironment(reduceMotion: reduceMotion)
        host = UIHostingController(rootView: OriginalRewardVisualHarness(model: model, environment: environment))
        let scene = try XCTUnwrap(UIApplication.shared.connectedScenes.compactMap { $0 as? UIWindowScene }.first)
        previousWindow = scene.windows.first(where: \.isKeyWindow)
        window = UIWindow(windowScene: scene)
        window.frame = scene.coordinateSpace.bounds
        window.overrideUserInterfaceStyle = .light
        window.rootViewController = host
        window.makeKeyAndVisible()
        host.view.frame = window.bounds
        host.view.setNeedsLayout()
        host.view.layoutIfNeeded()
    }

    func restoredModel() -> AppModel {
        model.flushPendingSaves()
        return AppModel(saveDirectory: directory, runsTimer: false, feedbackEnabled: false, analyticsIdentityStore: identity)
    }

    func close() {
        window.isHidden = true
        window.rootViewController = nil
        previousWindow?.makeKeyAndVisible()
        model.flushPendingSaves()
        try? FileManager.default.removeItem(at: directory)
    }
}

/// These attachments are sampled views of the real SwiftUI screens for human
/// review, not a claim of frame-accurate animation matching to Pawdoku. Scene
/// phase and six prior check-in dates are explicit test fixtures. The internal
/// motion override verifies view branches; it does not change or verify the
/// device's actual system accessibility setting.
final class OriginalRewardVisualTests: XCTestCase {
    @MainActor private func pause(_ milliseconds: UInt64) async throws {
        try await Task.sleep(nanoseconds: milliseconds * 1_000_000)
    }

    @MainActor private func capture(_ rig: OriginalRewardVisualRig, _ name: String) throws {
        rig.host.view.layoutIfNeeded()
        var drawn = false
        let image = UIGraphicsImageRenderer(bounds: rig.window.bounds).image { _ in
            // Do not request a new screen-update transaction that deliberately
            // settles an in-progress transition before capturing its appearance.
            drawn = rig.host.view.drawHierarchy(in: rig.host.view.bounds, afterScreenUpdates: false)
        }
        XCTAssertTrue(drawn)
        let pixels = try XCTUnwrap(image.cgImage?.dataProvider?.data) as Data
        XCTAssertGreaterThan(Set(pixels).count, 16, "An empty frame is not usable visual evidence.")
        let attachment = XCTAttachment(image: image)
        attachment.name = name + (rig.environment.reduceMotion ? "-view-override-not-system-setting" : "")
        attachment.lifetime = .keepAlways
        add(attachment)
    }

    @MainActor private func prepareSixPriorClaims(_ model: AppModel) throws {
        XCTAssertEqual(model.config.checkInCycleDays, 7, "This fixture describes the provisional seven-day Demo cycle.")
        let today = Date()
        for daysAgo in stride(from: 6, through: 1, by: -1) {
            let outcome = model.progress.claimCheckIn(on: today.addingTimeInterval(-Double(daysAgo) * 86_400), config: model.config)
            guard case .claimed = outcome else { return XCTFail("The six prior days must be generated by the real claim operation.") }
        }
        model.now = today
        model.save()
        XCTAssertEqual(model.progress.checkIn.cycleDay, 6)
        XCTAssertEqual(model.progress.checkIn.streak, 6)
        XCTAssertEqual(model.progress.checkIn.completedCycles, 0)
        XCTAssertTrue(model.progress.checkIn.canClaim(on: today))
        model.screen = .home
    }

    @MainActor private func finish(_ model: AppModel, won: Bool) throws {
        let session = try XCTUnwrap(model.session)
        if won {
            for cell in session.puzzle.solution { model.submit(cell) }
        } else {
            let wrong = session.puzzle.regions.indices.filter { !session.puzzle.solution.contains($0) }
            XCTAssertGreaterThanOrEqual(wrong.count, session.lives)
            for cell in wrong.prefix(session.lives) { model.submit(cell) }
        }
        XCTAssertEqual(model.session?.status, won ? .won : .lost)
        XCTAssertNil(model.errorMessage)
    }

    @MainActor func testWinAndLossEntrancesRenderActualRootAndKeepResultSaved() async throws {
        for won in [true, false] {
            let rig = try OriginalRewardVisualRig()
            defer { rig.close() }
            let label = won ? "win" : "loss"
            try await pause(100)
            try capture(rig, "result-\(label)-01-before")
            try finish(rig.model, won: won)
            try await pause(60)
            try capture(rig, "result-\(label)-02-early-sample")
            try await pause(260)
            try capture(rig, "result-\(label)-03-settled")
            let result = try XCTUnwrap(rig.model.session)
            rig.model.submit(result.puzzle.solution[0])
            XCTAssertEqual(rig.model.session, result, "Rendering the result must not unlock terminal board input.")
            XCTAssertEqual(rig.restoredModel().session, result, "The visual result must describe the saved game result.")
        }
    }

    @MainActor func testCycleGiftReadyAndClaimedScreensDoNotGrantRewardsByRendering() async throws {
        let rig = try OriginalRewardVisualRig(configure: prepareSixPriorClaims)
        defer { rig.close() }
        try await pause(80)
        let before = rig.model.progress
        rig.model.screen = .checkIn
        try await pause(60)
        try capture(rig, "checkin-cycle-01-ready-early-sample")
        try await pause(850)
        try capture(rig, "checkin-cycle-02-ready-settled")
        XCTAssertEqual(rig.model.progress, before, "Showing a claimable gift cannot change any player state.")
        rig.model.claim()
        XCTAssertEqual(rig.model.progress.checkIn.streak, 7)
        XCTAssertEqual(rig.model.progress.checkIn.cycleDay, 7)
        XCTAssertEqual(rig.model.progress.checkIn.completedCycles, 1)
        XCTAssertFalse(rig.model.progress.checkIn.canClaim(on: rig.model.now))
        XCTAssertEqual(rig.model.progress.bonusHints, before.bonusHints + rig.model.config.dailyHintReward)
        XCTAssertEqual(rig.model.progress.bonusDirect, before.bonusDirect + rig.model.config.cycleDirectReward)
        try await pause(100)
        try capture(rig, "checkin-cycle-03-claimed-after-business-action")
        let claimed = rig.model.progress
        let restored = rig.restoredModel()
        XCTAssertEqual(restored.progress.checkIn, claimed.checkIn)
        XCTAssertEqual(restored.progress.bonusHints, claimed.bonusHints)
        XCTAssertEqual(restored.progress.bonusDirect, claimed.bonusDirect)
        XCTAssertEqual(restored.session, before.session, "Check-in must preserve the existing board.")
        rig.model.home()
        rig.model.screen = .checkIn
        try await pause(850)
        try capture(rig, "checkin-cycle-04-claimed-reentry")
        XCTAssertEqual(rig.model.progress, claimed)
        rig.model.claim()
        XCTAssertEqual(rig.model.progress, claimed, "A duplicate business request cannot claim the cycle twice.")
    }

    @MainActor func testCycleGiftBackgroundAndPageExitLeaveNoLateVisibleEffects() async throws {
        let rig = try OriginalRewardVisualRig(configure: prepareSixPriorClaims)
        defer { rig.close() }
        try await pause(80)
        let before = rig.model.progress
        rig.model.screen = .checkIn
        try await pause(60)
        try capture(rig, "checkin-lifecycle-01-before-background")
        rig.environment.phase = .background
        try await pause(100)
        try capture(rig, "checkin-lifecycle-02-background-environment")
        try await pause(850)
        rig.environment.phase = .active
        try await pause(100)
        try capture(rig, "checkin-lifecycle-03-return-after-expiry")
        rig.model.home()
        try await pause(60)
        rig.model.screen = .checkIn
        try await pause(60)
        rig.model.home()
        try await pause(850)
        try capture(rig, "checkin-lifecycle-04-home-after-exit")
        XCTAssertEqual(rig.model.screen, .home)
        XCTAssertEqual(rig.model.progress, before)
        XCTAssertTrue(rig.model.progress.checkIn.canClaim(on: rig.model.now))
        XCTAssertNil(rig.model.errorMessage)
    }

    @MainActor func testReducedMotionGiftReadyAndClaimedStatesRemainOperable() async throws {
        let rig = try OriginalRewardVisualRig(reduceMotion: true, configure: prepareSixPriorClaims)
        defer { rig.close() }
        try await pause(80)
        rig.model.screen = .checkIn
        let before = rig.model.progress
        try await pause(60)
        try capture(rig, "checkin-reduce-motion-01-ready")
        try await pause(850)
        try capture(rig, "checkin-reduce-motion-02-ready-after-expiry")
        XCTAssertEqual(rig.model.progress, before)
        XCTAssertTrue(rig.model.progress.checkIn.canClaim(on: rig.model.now))
        rig.model.claim()
        try await pause(80)
        try capture(rig, "checkin-reduce-motion-03-claimed")
        XCTAssertEqual(rig.model.progress.checkIn.completedCycles, 1)
        XCTAssertFalse(rig.model.progress.checkIn.canClaim(on: rig.model.now))
        XCTAssertEqual(rig.restoredModel().progress.checkIn, rig.model.progress.checkIn)
    }

    @MainActor func testReducedMotionWinAndLossUseTheActualResultViews() async throws {
        for won in [true, false] {
            let rig = try OriginalRewardVisualRig(reduceMotion: true)
            defer { rig.close() }
            try await pause(80)
            try finish(rig.model, won: won)
            try await pause(60)
            try capture(rig, "result-reduce-motion-\(won ? "win" : "loss")-early-sample")
            try await pause(250)
            try capture(rig, "result-reduce-motion-\(won ? "win" : "loss")-settled")
            XCTAssertEqual(rig.model.session?.status, won ? .won : .lost)
            XCTAssertEqual(rig.restoredModel().session, rig.model.session)
        }
    }

    @MainActor func testCurrentPackEightByEightProgressLayoutIsCapturedWithoutChangingTheBoard() async throws {
        let pack = try XCTUnwrap(Bundle.main.url(forResource: "levels", withExtension: "json"))
        let puzzles = try JSONDecoder().decode([Puzzle].self, from: Data(contentsOf: pack))
        let level = try XCTUnwrap(puzzles.first { $0.size == 8 })
        let rig = try OriginalRewardVisualRig { $0.start(level: level.id) }
        defer { rig.close() }
        let before = try XCTUnwrap(rig.model.session)
        XCTAssertEqual(before.puzzle.size, 8)
        XCTAssertEqual(before.lives, 3)
        try await pause(120)
        try capture(rig, "gameplay-current-pack-eight-by-eight-progress")
        XCTAssertEqual(rig.model.session, before)
        XCTAssertNil(rig.model.errorMessage)
    }
}
